export const certifications = [
  {
    id: "mastercard-forage",
    name: "Cybersecurity Job Simulation",
    issuer: "Mastercard (via Forage)",
    category: "Security",
    date: "May 2026",
    description:
      "Served as an analyst on Mastercard's Security Awareness Team. Identified and reported security threats such as phishing, and implemented training courses for teams needing more robust security awareness.",
    file: "/documents/certification/FORAGE/MASTECARD CYBERSECURITY FORAGE.pdf",
    highlight: true,
  },
  {
    id: "ai-simplilearn",
    name: "Introduction to Artificial Intelligence",
    issuer: "Simplilearn",
    category: "AI/ML",
    date: "2024",
    description: "Comprehensive introduction to AI concepts, machine learning fundamentals, and practical applications.",
    file: "/documents/certification/Artificial Intelligence.pdf",
    highlight: false,
  },
  {
    id: "ai-generalist",
    name: "Generative AI Mastermind",
    issuer: "Outskill",
    category: "AI/ML",
    date: "2024",
    description: "Advanced course on Generative AI, covering LLMs, prompt engineering, and real-world AI application development.",
    file: "/documents/certification/Het_Patel_Certificate_AI_Generalist.pdf",
    highlight: false,
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing Course",
    issuer: "Cursa",
    category: "Marketing",
    date: "2024",
    description: "Complete digital marketing certification covering SEO, social media, and online campaign strategy.",
    file: "/documents/certification/Digital Marketing Certificate(CMS).pdf",
    highlight: false,
  },
  {
    id: "linux-iitb",
    name: "Linux Training",
    issuer: "Spoken Tutorial Project – IIT Bombay",
    category: "Systems",
    date: "2024",
    description: "Hands-on Linux training covering command-line tools, shell scripting, and system administration.",
    file: "/documents/certification/HETKUMAR-PATEL-Participant-Certificate Linux.pdf",
    highlight: false,
  },
  {
    id: "php-mysql-iitb",
    name: "PHP and MySQL Training",
    issuer: "Spoken Tutorial Project – IIT Bombay",
    category: "Web Dev",
    date: "2024",
    description: "Server-side web development training with PHP and MySQL, including database design and backend development.",
    file: "/documents/certification/HETKUMAR-PATEL-Participant-Certificate.pdf",
    highlight: false,
  },
  {
    id: "javascript-iitb",
    name: "JavaScript Training",
    issuer: "Spoken Tutorial – IIT Bombay",
    category: "Web Dev",
    date: "2023",
    description: "Core JavaScript programming including ES6+, DOM manipulation, async programming, and browser APIs.",
    file: "/documents/certification/SPOKEN TUTORIAL JavaScript Training.pdf",
    highlight: false,
  },
  {
    id: "selenium-simplilearn",
    name: "Introduction to Selenium",
    issuer: "Simplilearn",
    category: "Testing",
    date: "2024",
    description: "Automated browser testing using Selenium WebDriver with test scripts for web application quality assurance.",
    file: "/documents/certification/Introduction to Selenium.pdf",
    highlight: false,
  },
  {
    id: "seo-simplilearn",
    name: "Introduction to SEO",
    issuer: "Simplilearn",
    category: "Marketing",
    date: "2024",
    description: "Search Engine Optimization fundamentals including on-page SEO, keyword research, and technical optimization.",
    file: "/documents/certification/Introduction to SEO.pdf",
    highlight: false,
  },
  {
    id: "matlab-simplilearn",
    name: "Introduction to MATLAB",
    issuer: "Simplilearn",
    category: "AI/ML",
    date: "2024",
    description: "MATLAB programming for engineering and machine learning, covering matrix operations and data analysis.",
    file: "/documents/certification/MATLAB certificate.pdf",
    highlight: false,
  },
  {
    id: "computer-networks",
    name: "Computer Networks",
    issuer: "Advance Institute of Technology and Management",
    category: "Networking",
    date: "2023",
    description: "Fundamental networking concepts including protocols, OSI model, TCP/IP, and network architecture.",
    file: "/documents/certification/HET.pdf",
    highlight: false,
  },
];

export type Certification = (typeof certifications)[number];
